# Default Configuration
default: &default
  model_path: "/home/sds262_yc958/palmer_scratch/Llama-2-7b-chat-hf/models--meta-llama--Llama-2-7b-chat-hf/snapshots/92011f62d7604e261f748ec0cfe6329f31193e33"

# Chatbot Configuration
chatbot_model:
  <<: *default
  rag: False
  finetune: True
  finetune_model_path: "./results/Llama-2-7b-spider"

# RAG Configuration
rag_config:
  documents: [
    "https://dev.mysql.com/doc/refman/8.0/en/select.html",
    "https://dev.mysql.com/doc/refman/8.0/en/update.html",
    "https://dev.mysql.com/doc/refman/8.0/en/table.html",
    "https://dev.mysql.com/doc/refman/8.0/en/union.html",
    "https://dev.mysql.com/doc/refman/8.0/en/values.html",
    "https://dev.mysql.com/doc/refman/8.0/en/delete.html",
  ]

# Finetuning Configuration
model_config: 
  <<: *default
  access_token: "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"
  new_model: "./results/llama-2-7b-spider"
  dataset_name: "KaifengGGG/spider_sql_schema"

q_lora_parameters:
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.1

bitsandbytes_parameters:
  use_4bit: True
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_quant_type: "nf4"
  use_nested_quant: False

training_arguments:
  output_dir: "./results"
  num_train_epochs: 1
  fp16: False
  bf16: False
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  gradient_checkpointing: True
  max_grad_norm: 0.3
  learning_rate: 0.0002
  weight_decay: 0.001
  optim: "paged_adamw_32bit"
  lr_scheduler_type: "cosine"
  max_steps: -1
  warmup_ratio: 0.03
  group_by_length: True
  save_steps: 0
  logging_steps: 25

sft_parameters:
  max_seq_length: null
  packing: False
  device_map: {"": 0}
