chatbot_model:
  path: "/home/sds262_kg797/palmer_scratch/Llama-2-7b-chat-hf/models--meta-llama--Llama-2-7b-chat-hf/snapshots/92011f62d7604e261f748ec0cfe6329f31193e33"
  rag: True

documents: [
  "https://scholar.google.com/citations?user=JzK8uYAAAAAJ",
  "https://yale-nlp.github.io/cpsc477/",
]