chatbot_model:
  path: "/home/sds262_kg797/palmer_scratch/Llama-2-7b-chat-hf/models--meta-llama--Llama-2-7b-chat-hf/snapshots/92011f62d7604e261f748ec0cfe6329f31193e33"
  rag: True

documents: [
  "https://dev.mysql.com/doc/refman/8.0/en/select.html",
  "https://dev.mysql.com/doc/refman/8.0/en/update.html",
  "https://dev.mysql.com/doc/refman/8.0/en/table.html",
  "https://dev.mysql.com/doc/refman/8.0/en/union.html",
  "https://dev.mysql.com/doc/refman/8.0/en/values.html",
  "https://dev.mysql.com/doc/refman/8.0/en/delete.html",
]